### ISSUE TITLE
Lua error: dissect_tcp_pdus dissect_func: ... v2g.lua:166: attempt to index a nil value

### ISSUE THREAD

**Issue by skrtre** [ChargePoint/wireshark-v2g#41]
Build standalone plugin for Linux (Ubuntu 22.04, Wireshark 4.0.3). No errors or warnings during build process but when analyzing V2GTP packets the Lua error. Any ideas how to fix?

**Comment by Gomox11** [comment]
@skrtre I run into the exact same issue with "main" and the "0.6.0" tag. Makes the plugin impossible to use for me. Did you find any solution yourself? Or does another developer have any advice?

**Comment by Gomox11** [comment]
So here is what I did from a "clean" state (no wireshark installed, no plugins installed, Ubuntu 20.04 LTS).

## Standalone

Following the README for a standalone plugin installation:
- sudo add-apt-repository ppa:wireshark-dev/stable -y
- sudo apt-get install tshark wireshark wireshark-dev
- git clone https://github.com/ChargePoint/wireshark-v2g.git
- mkdir wireshark-v2g/build && cd wireshark-v2g/build
- cmake ..
- make
- sudo make install

... which ends in:
```
Install the project...
-- Install configuration: "Debug"
-- Installing: /usr/local/lib/wireshark/plugins/4.0/epan/v2gexi.so
-- Set runtime path of "/usr/local/lib/wireshark/plugins/4.0/epan/v2gexi.so" to ""
-- Installing: /usr/local/lib/wireshark/plugins/4.0/../v2g.lua
```

But if I then try to run wireshark, it says:

```
wireshark          
wireshark: symbol lookup error: wireshark: undefined symbol: wslua_plugins_get_descriptions
```

**Comment by chardin-cpi** [comment]
This should be fixed now - loaded a Wireshark with a standalone and got the plugin registered with the symbols
