### ISSUE TITLE
Unknown EXI message after supportedAppProtocol Request and Response

### ISSUE THREAD

**Issue by qq3330108912** [ChargePoint/wireshark-v2g#55]
<img width="1466" alt="654" src="https://github.com/ChargePoint/wireshark-v2g/assets/39181436/52e5018d-6d48-47f0-8adf-244cf08b5608">

Why can't my agreement be parsed? I can communicate with EVCC normally

**Comment by chardin-cpi** [comment]
please send the pcap file if possible? this might be a bug in selecting the supported protocol or running thru tshark with verbose can sometimes give more information with the hexdump to allow some data for debug.

**Comment by jhart-cpi** [comment]
Closing issue, appears stale.
