### ISSUE TITLE
Extended SDP (J3400 RP) decoding support

### ISSUE THREAD

**Issue by JeremyWhaling** [ChargePoint/wireshark-v2g#64]
I'm starting work on adding support for extended SDP as defined in J3400 recommended practice. My plan is just to add to the SDP table and other various parts of the Lua script without any major structural changes. I wanted to point this out in case there's changes to the Lua script as part of the pending pull request (https://github.com/ChargePoint/wireshark-v2g/pull/62).

**Comment by chardin-cpi** [comment]
time wise - will likely rebase after the other changes - talked to @jhart-cpi about how we need to pass the grammar for 20 so we will need to modify the Lua but keep going with this change since we will try to avoid the conflicts as possible.

**Comment by JeremyWhaling** [comment]
Sounds good. My main modifications are to the SDP table, adding some helper functions for things like inlet port type, and within the dissector function itself I am differentiating the logic from "regular" SDP by looking at payload length (so the sections under if payload_type_name == "SDP REQUEST" and "SDP RESPONSE" will grow). Unlike the previous "SDP with EMSP", the SDP header is the same (0x9000 / 0x9001), so this seems to be the only way to attack this (maybe something to bring up in committee).
